### ISSUE TITLE
Add new array format support

### ISSUE THREAD

**Issue by fanphp** [junichi11/netbeans-php-enhancements#10]
Hi, 
actually this plugin does not work with new PHP array notation  `[]`; do you think it is possible to fix this "issue"  ?

Example: $a = [ 'bar' => 'baz'];   //This does not work

**Comment by junichi11** [comment]
Does it mean a typing hook feature?

**Comment by fanphp** [comment]
yes, something like that!
Actually, if I type
```
<?php
$work = array( 'bar' => .... );    << plugin recognizes the array structure and works well

$dontWork = [ 'bar' => ....] ;    << plugin does not recognize the new PHP array notation  and does not work
```

?>
Thanks in advance!

**Comment by junichi11** [comment]
Okay, I'll fix it. Thanks.

**Comment by junichi11** [comment]
Fixed.

@fanphp Could you please test it? (Please try testing some cases if possible)
https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v0.9.0 (0.9.0.1-dev)
If there is no problem, I'll update version number. Then, create a new nbm.

#### NOTE
Now, It works inside of both array() and [].
It means it works also array access cases. e.g. 
```php
$array = ["foo" => "bar"];
$array[|]; // here
``` 

But I think that "=" is not used there. If you know the case using it, please let me know.

Thanks.

**Comment by junichi11** [comment]
The following is valid:
```php
$array1 = ["foo" == "bar"];
$array2 = ["foo" === "bar"];
```
So, I'll implement as the following:
- just remove ">" before "=" is inserted when the caret position is  here "=>|" (i.e. "=>"  => "==") 
- just do nothing when the caret position is here "==|"  (i.e. "==" => "===")

**Comment by fanphp** [comment]
Hi,
it works well now, I've downloaded and tested the new plugin version. Thanks at all!!!!

**Comment by junichi11** [comment]
Thanks for testing it :+1: 
I'll update version after I committed the above changes.

**Comment by junichi11** [comment]
New version is available:
https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v0.9.1
