### ISSUE TITLE
Add code folding for both short and long style arrays.

### ISSUE THREAD

**Issue by kwfinken** [junichi11/netbeans-php-enhancements#12]
Doing programming in PHP for Drupal, much of what is done is in the form of very long render arrays.  It would be very useful to be able to collapse such arrays and focus on logic instead of arrays.

**Comment by junichi11** [comment]
Probably, we cannot fix it. 
You have already submitted it to the NB bugzilla [1].

[1] https://netbeans.org/bugzilla/show_bug.cgi?id=262471 

Thanks.
