### ISSUE TITLE
Add netbeans 8.2 support

### ISSUE THREAD

**Issue by jetexe** [junichi11/netbeans-php-enhancements#13]
Your plugin work nice in thet platform, bun in plugin search it not shown

**Comment by junichi11** [comment]
Done. 

https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v0.10.0

Now, it's available in NetBeans Plugin Portal. But it is not verified yet. If you want to install directly in IDE, please wait a while.

Thanks for reporting!
