### ISSUE TITLE
Array convert in current file by hostkey

### ISSUE THREAD

**Issue by 2557530** [junichi11/netbeans-php-enhancements#15]
Can you make hotkey for convert array to short syntax in current editing file? 
I don't use projects, use netbeans as editor, and i very need this cool function.

**Comment by junichi11** [comment]
@2557530 I noticed this now, sorry.

You can set a shortcut key :)
Please set your shortcut key to Tools > Options > KeyMap > Convert to short array syntax
![_107](https://user-images.githubusercontent.com/738383/37133191-17dc2172-22d5-11e8-99f3-2643e0bf3fc9.png)

**Comment by 2557530** [comment]
thank you very much) 
-------- Исходное сообщение --------От: Junichi Yamamoto <notifications@github.com> Дата: 08.03.18  11:33  (GMT+07:00) Кому: junichi11/netbeans-php-enhancements <netbeans-php-enhancements@noreply.github.com> Копия: 2557530 <2557530@gmail.com>, Mention <mention@noreply.github.com> Тема: Re: [junichi11/netbeans-php-enhancements] Array convert in current file by hostkey (#15) 
@2557530 I noticed this now, sorry.
You can set a shortcut key :)

Please set your shortcut key to Tools > Options > KeyMap > Convert to short array syntax



—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/junichi11/netbeans-php-enhancements","title":"junichi11/netbeans-php-enhancements","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/junichi11/netbeans-php-enhancements"}},"updates":{"snippets":[{"icon":"PERSON","message":"@junichi11 in #15: @2557530 I noticed this now, sorry.\r\n\r\nYou can set a shortcut key :)\r\nPlease set your shortcut key to Tools \u003e Options \u003e KeyMap \u003e Convert to short array syntax\r\n![_107](https://user-images.githubusercontent.com/738383/37133191-17dc2172-22d5-11e8-99f3-2643e0bf3fc9.png)\r\n\r\n\r\n "}],"action":{"name":"View Issue","url":"https://github.com/junichi11/netbeans-php-enhancements/issues/15#issuecomment-371375855"}}}
