### ISSUE TITLE
Disable displaying errors from Vendor

### ISSUE THREAD

**Issue by vitaly-los** [junichi11/netbeans-php-enhancements#18]
All PHP frameworks have folder Vendor, but Netbeans always find errors here

If add vendor in Properties-> Ignored Folders, errors is not displayed, but after that you can't use autocomplete for code or jump to definition class, functions. This also removes the folder from the project view. 

Can you add option to exclude vendor directory from code analysis in your plugin?

![netbeans](https://user-images.githubusercontent.com/38357863/47451412-58ee9400-d7d0-11e8-87ff-51f73179fc06.png)

**Comment by junichi11** [comment]
If it's a correct syntax, this is a bug. So, please report it to the JIRA with a simple sample code: https://issues.apache.org/jira/projects/NETBEANS/issues

**Comment by junichi11** [comment]
Submitted: https://issues.apache.org/jira/browse/NETBEANS-1552

**Comment by vitaly-los** [comment]
@junichi11  
Maybe I'm not explain myself clear, because my English is not very good
Netbeans ALWAYS display errors in Vendor folder in Laravel, YII2, Symphony etc. Screenshot I give just as an example. 
Another IDEs like PHPStorm doesn't check syntax in Vendor folder, and even show warning message if you try to change code in this directory.  So I think your PHP plugin is the right place to fix such errors in PHP project
So I try jira, maybe someone can time for it

**Comment by junichi11** [comment]
@vitaly-los 

> Maybe I'm not explain myself clear, because my English is not very good

Please don't worry. I'm also not good at English :) 
Maybe, if you write example code and attach screenshots, we can understand, I suppose. So please feel free to report your problems. It would be helpful for many PHP users. 

> So I think your PHP plugin is the right place to fix such errors in PHP project

No, this plugin is a bad place. If there are syntax errors, it should be fixed in NetBeans(not a plugin).
I'm an Apache NetBeans committer. So I can look at problems.

Thanks.

**Comment by vitaly-los** [comment]
@junichi11 
I try to explain it here
https://issues.apache.org/jira/browse/NETBEANS-1553
I think, it's better if you can install laravel, and see errors yourself. 
Another time I report issue on jira, hope someone can fix it. 
P.S thanks for Rainbow plugin, it looks great
