### ISSUE TITLE
“Convert to short array syntax” appears in context menu of Java projects

### ISSUE THREAD

**Issue by maffe** [junichi11/netbeans-php-enhancements#21]
The context menu entry should not appear on non-PHP projects.
![grafik](https://user-images.githubusercontent.com/515302/63775580-ed89bd00-c8df-11e9-934f-9ac3a53f5681.png)

**Comment by junichi11** [comment]
Fixed: https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.0.0 v1.0.0.1
