### ISSUE TITLE
The plugin PHP Editor is requested in implementation version 2.

### ISSUE THREAD

**Issue by corexz** [junichi11/netbeans-php-enhancements#22]
in apache netbeans 12.2 , when try install PHP Enhancements , i got his message 
"The plugin PHP Editor is requested in implementation version 2."
and can not install the plugin.

**Comment by junichi11** [comment]
Yes, I know it. I'll create a nbm for 12.2 later. So please wait a while. Unfortunately, we can't provide it via the Plugin Portal. So, I'll upload it to GitHub releases.

**Comment by junichi11** [comment]
Done: https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0 
Please give it a try. Thanks!

**Comment by Ashkikhan** [comment]
Great Work junichi11, thank you and all people working for keeping NetbeansIDE alive.

**Comment by TCAby** [comment]
I got the message at NB 12.3 version. Forum's guys recomended me update to 12.4 - I've did it, but the same!

**Comment by junichi11** [comment]
@TCAby May I have your version number of the plugin? (Is it 1.2.0?)

**Comment by jcvasquez07** [comment]
I'm using 12.5, installed it from [https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0](https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0)

**Comment by junichi11** [comment]
I've rebuilt it with NetBeans 12.5: https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0 (netbeans-php-enhancements-1.2.0-nb125.nbm)
So, please try to use it with NetBeans 12.5

**Comment by larka06** [comment]
I install the top plugin "netbeans-php-enhancements-1.2.0-nb125.nbm" but I still have the problem of no PHP editor.

**Comment by junichi11** [comment]
@larka06 May I have your version number of NetBeans?

**Comment by authentictech** [comment]
> @larka06 May I have your version number of NetBeans?

For me, same issue in Netbeans 12.6.

**Comment by evambenitez** [comment]
Hola! Mismo problema en Netbeans 12.6.
Tenéis solución?

**Comment by MoniTam** [comment]
Intento Instalar el plugin  PHP CakePHP Framework y me sale esto es el ultimo plugin que me falta alguien sabe donde encontrarlo :(
Some plugins require plugin PHP Editor to be installed.
The plugin PHP Editor is requested in implementation version 2.  The following plugin is affected:       PHP CakePHP Framework

**Comment by junichi11** [comment]
Rebuilt with NetBeans 12.6: https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0 (netbeans-php-enhancements-1.2.0-nb126.nbm)

**Comment by axelgervaisberi** [comment]
Hi juinichi11 I installed the plugin in NetBeans 12.6 but I still have the problem of no PHP Editor.

**Comment by junichi11** [comment]
I'm going to recreate a nbm for NB13. (This problem should be resolved in NB13)

**Comment by atabak** [comment]
hi, i have same problem

**Comment by larka06** [comment]
Has anyone found a solution to this problem?  I read and try but same results; No PHP Editor.

**Comment by junichi11** [comment]
@atabak @larka06 What is the version number of NetBeans?
