### ISSUE TITLE
Can not install on Netbeans 12.2 :: The plugin PHP Editor is required in implementation version 2

### ISSUE THREAD

**Issue by uran1980** [junichi11/netbeans-php-enhancements#23]
Hi
Can not install on Netbeans 12.2
The plugin PHP Editor is required in implementation version 2

```
Product Version: Apache NetBeans IDE 12.2
Java: 11.0.9.1; OpenJDK 64-Bit Server VM 11.0.9.1+1-Ubuntu-0ubuntu1.20.04
Runtime: OpenJDK Runtime Environment 11.0.9.1+1-Ubuntu-0ubuntu1.20.04
System: Linux version 5.4.0-56-generic running on amd64; UTF-8; ru_RU (nb)
User directory: /home/uran1980/.netbeans/12.2
Cache directory: /home/uran1980/.cache/netbeans/12.2
```

![2020-12-09-01](https://user-images.githubusercontent.com/1616795/101685817-e0f78c80-3a70-11eb-8b31-71527a3ea955.png)

**Comment by uran1980** [comment]
download latest version 1.2 `netbeans-php-enhancements-1.2.0.nbm` and all work now.

**Comment by TCAby** [comment]
I got the message at NB 12.3 version. Forum's guys recomended me update to 12.4 - I've just did it, but the same!

**Comment by RonanRBR** [comment]
I have the same problema, with NB 12.4

**Comment by junichi11** [comment]
Did you use this?: https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0

**Comment by RonanRBR** [comment]
Yes, thank you.


Atenciosamente,
*Ronan Ribeiro* <https://www.linkedin.com/in/RonanRBR/>
+55 85 98761-1448
+55 85 3099-4887 (Comercial)
-------------------------------------------


Em qua., 22 de set. de 2021 às 01:04, Junichi Yamamoto <
***@***.***> escreveu:

**Comment by junichi11** [comment]
I've rebuilt it with NetBeans 12.5: https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0 (netbeans-php-enhancements-1.2.0-nb125.nbm)
So, please try to use it with NetBeans 12.5

**Comment by vgip** [comment]
Please update the plugin in the NetBeans repository. I can't install this plugin with NetBeans 12.6. 

I use netbeans-php-enhancements-1.2.0-nb125.nbm - worked. 

Many beginners will not be able to install the plugin just because trying to install it from the official Netbeans repository causes an error: "The plugin PHP Editor is requested in implementation version 2. The following plugin is affected: PHP Enhancements".

**Comment by cseoneohs** [comment]
Hello, same problem for me. But yes it's works with netbeans-php-enhancements-1.2.0-nb125.nbm
For download and install go here :
https://github.com/junichi11/netbeans-php-enhancements/releases

**Comment by junichi11** [comment]
Rebuilt with NetBeans 12.6: https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0 (netbeans-php-enhancements-1.2.0-nb126.nbm)
