### ISSUE TITLE
The plugin PHP Editor is requested in implementation version 2.

### ISSUE THREAD

**Issue by corexz** [junichi11/netbeans-php-enhancements#24]
Hello 
when try to intall the plugin, I got this message and I could't continue installing the plugin
the message is " The plugin PHP Editor is requested in implementation version 2. , The following plugin is affected:       PHP Enhancements".

**Comment by junichi11** [comment]
Did you try using this?: https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0

**Comment by uran1980** [comment]
https://github.com/junichi11/netbeans-php-enhancements/issues/23

**Comment by imrevaczi** [comment]
OK, but what is PHP editor plugin? where is it found?

**Comment by junichi11** [comment]
> OK, but what is PHP editor plugin? where is it found?

It means the PHP editor module of NetBeans. (Not a community plugin)
