### ISSUE TITLE
Netbeans 12.2 : cannot install

### ISSUE THREAD

**Issue by eviweb** [junichi11/netbeans-php-enhancements#25]
Dear @junichi11,

thanks for your nice job.
Unfortunately I cannot install this module on NetBeans 12.2, please see the error message:
![netbeans-php-enhancements-error](https://user-images.githubusercontent.com/1310382/105823621-ab294b80-5fbd-11eb-8d72-1cbb8c35bc36.png)

Here are my NetBeans version information:
![netbeans-version-info](https://user-images.githubusercontent.com/1310382/105823721-ca27dd80-5fbd-11eb-80f7-ff3ae0744eb2.png)

Is there something I can do on my side?

Thanks

**Comment by uran1980** [comment]
@see https://github.com/junichi11/netbeans-php-enhancements/issues/23

**Comment by junichi11** [comment]
@eviweb Please use 1.2.0: https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0

**Comment by eviweb** [comment]
Dear @junichi11,
sorry I missed the previous issue.
It works great thanks.
Any plan for the integration of this release in the UC ?
Best

**Comment by junichi11** [comment]
@eviweb No problem. Great to hear :)

> Any plan for the integration of this release in the UC ?

I would like to do that. However, we can't do that at the moment... Unfortunately, the Plugin Portal provides support for only LTS versions. (We can't add nbms for feature release versions. e.g. 12.1, 12.2)See: https://issues.apache.org/jira/browse/NETBEANS-5064

**Comment by matigere** [comment]
Hi @all. is there are solution for php editor for wordpress blog/cms and hibernate? the current posted solutions dont seem to work at all

**Comment by matigere** [comment]
@junichi11 this aare the errors messages i get when installing netbeans 12.4
(1) The plugin PHP Editor is requested in implementation version 2.  The following plugin is affected:
PHP WordPress Blog/CMS
(2) The plugin Freemarker Integration is requested in implementation version 238.  The following plugin is affected:       Hibernate
for the second issue the suggested solution requires a complete uninstall before implementing it

**Comment by junichi11** [comment]
@matigere 
> (1) The plugin PHP Editor is requested in implementation version 2. 

Did you try to use version 1.2.0? https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.2.0
May I have your plugin version?

The following plugin is affected:
> PHP WordPress Blog/CMS
> (2) The plugin Freemarker Integration is requested in implementation version 238. The following plugin is affected:       Hibernate
> for the second issue the suggested solution requires a complete uninstall before implementing it

Please submit your problem to the plugin's issue tracker.

**Comment by matigere** [comment]
@junichi11 
I already installed the plug in. i am also baffled that php wordpress cannot access the plugin. what am looking for is a workaround that may be able deal with the issue

**Comment by junichi11** [comment]
Please don't write about the wp plugin's problem. As I wrote above, please submit your problem to the plugin's issue tracker: https://github.com/junichi11/netbeans-wordpress-plugin Before that, please try the new version of the WP plugin.

**Comment by matigere** [comment]
I found the plugin at the following url

https://github.com/junichi11/netbeans-wordpress-plugin/releases
@junichi11 : thanks
