### ISSUE TITLE
Double arrow for match expressions and arrow functions

### ISSUE THREAD

**Issue by adamturcsan** [junichi11/netbeans-php-enhancements#27]
PHP7.4 brought a new feature with a new snytax, called arrow functions.

```php
$func = fn() =>  'example return value';
```

PHP8's new match expression also uses an array...ish/like syntax for defining patterns.
```php
match (true) {
    firstCondition() => $something,
    secondCondition() => $otherThing
}
```

As a user of this plugin I got used to typing double arrows with only the equal sign when it is appropriate, so I noticed that I always missed the &gt; sign. 

Match expressions can have a lot more complex syntax for the patterns, so I don't really know whether it is solvable, but it would be awesome.

**Comment by junichi11** [comment]
> Match expressions can have a lot more complex syntax for the patterns, so I don't really know whether it is solvable, but it would be awesome.

Maybe,  are you concerned about the following case?
```php

match (true) {
    $boolean == true => 1,
    default => 0,
}
```

In this case, if we type `=` after `$boolean`, `=>` is inserted.
However, if we type `=` after `=>`, `>` is deleted.

**Comment by junichi11** [comment]
I've created the dev version: https://github.com/junichi11/netbeans-php-enhancements/releases/tag/v1.3.0 (1.3.0.1-dev)
Please give it a try if you can test it :)
Please let me know if there is a problem.
Thanks.

**Comment by adamturcsan** [comment]
It seems to work perfectly. Thank you!

**Comment by junichi11** [comment]
Thank you for your verification! 
I'll upload the new version to the PP later.

**Comment by adamturcsan** [comment]
I saw your code now, so I could find some edge-cases:

```php
fn(&$value) => $value => 'a new assigned value';
```

When assignment happens, a double arrow is wrongly drawn again. It should only put another arrow if a new fn (or any other use cases, eg. array, match, etc.) happens. It behaves the same for arrays:
```php
[
    'aStringKey' => $aVariableToAssignAValue => 'a value'
]
```

These don't seem to be too common cases, but they are valid PHP.
It doesn't happen for match expressions though. (I only tested this for `match` before....)

**Comment by junichi11** [comment]
Yes, I recognize it :) (I wrote about that case in README as a Note. We have to delete `>`.)
Currently, it is handled for only match expressions.
e.g. 

```php
$test = match (true) {
    ["a" => "test"] => $test = 2,
}
```
Maybe, I can improve behavior for arrays and arrow functions as well.
Thanks.

**Comment by adamturcsan** [comment]
Great! Thanks!
